version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/backend/

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - "8001:8001"
    volumes:
      - ./frontend:/usr/src/frontend/
      - ./frontend/node_modules:/usr/src/frontend/node_modules
    depends_on:
      - backend