version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/backend/
    networks:
      static-network:
        ipv4_address: 172.23.0.3


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend-container
    ports:
      - "8080:8080"
    volumes:
      - /usr/src/frontend/node_modules
      - ./frontend:/usr/src/frontend/
    networks:
      static-network:
        ipv4_address: 172.23.0.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.23.0.0/16
